### ISSUE TITLE
Mobenter Freebuild2

### ISSUE THREAD

**Issue by Ceddix** [CraftTogetherDE/CraftBahn#3]
Der `/mobenter` Befehl, des CraftBahn Plugins scheint wohl in der **Freebuild 2** nicht zu funktionieren. Ich habe es mit mehrere Tieren (Füchse, Schafe, Pferde...) versucht, es kommt jedes mal folgende Meldung:
![Fehlermeldung](https://craft-together.de/~ceddix/uploads/javaw_QYT7gUx4DC.png)

**Comment by ghost** [comment]
Wenn es auf anderen Servern funktioniert, dann nimm doch mal das JAR-File von einem funktionierendem Server und update CraftBahn.jar für Freebuild2 ansonsten wüsste ich nich was in FB2 anders sein sollte.

**Comment by Ceddix** [comment]
Okay, scheint das Problem gelöst zu haben. Danke :D
