### ISSUE TITLE
Kleine Anregung für das Tabcomplete

### ISSUE THREAD

**Issue by Ceddix** [CraftTogetherDE/CraftBahn#4]
Die Fahrzielliste ist so aufgebaut, dass wenn ein Fahrziel auf mehreren Servern existiert, dem Spieler eine Liste angezeigt wird und er dort eine Welt aussuchen kann.:
![mehrere Fahrziele](https://craft-together.de/~ceddix/uploads/javaw_M6N73kjQzQ.png)

Für Leute die sich nicht so gerne durch ein Menu klicken, sondern lieber den Befehl schreiben, hatten wir die Möglichkeit eingebaut, dass man z.B. `/fahrziel BF-Nord freebuild1` eingeben kann. Letzteres ist jedoch **nicht tabcompletebar**.:
![Tabcomplete jetzt](https://craft-together.de/~ceddix/uploads/javaw_JPVT9479XH.png)

Hier wäre es praktisch, wenn man dort, direkt die nächsten Argumente vorgeschlagen bekommt. *(Eventuell sogar nur die Server, auf denen das Fahrziel auch existiert? 🤔)*

Grüße, Ceddix! 😄

**Comment by ghost** [comment]
Is mir auch die Tage nochmal aufgefallen.. stand schon auf meiner Imaginären ToDo-Liste..^^ Trotzdem Danke!
